/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'xcv58' at '11/7/15 10:15 PM' with Gradle 2.8
 *
 * @author xcv58, @date 11/7/15 10:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
